#!/usr/bin/env bash

# brew install arp-scan expect

unbuffer arp-scan -l -q -x -F '${ip}' | xargs -n1 -I% -P 0 sh -c 'nc -zG3 % 5555 2>/dev/null && adb connect % >/dev/null && echo "%\t$(adb -s % shell getprop ro.serialno)\t$(adb -s % shell getprop ro.build.fingerprint)" 2>/dev/null'
